name: ethereum_util
description: a collection of utility functions for Ethereum
version: 1.3.1
author: Peter Chung <touhonoob@gmail.com>
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  convert: ^3.0.0
  quiver: '>=2.0.0 <3.0.0'
  pointycastle_hcb:
    git: 
      url: https://github.com/kithau-hcb/pc-hcb.git
      ref: 'hcb-1.0.2'
  buffer: ^1.0.6
  equatable: ^1.2.5
  collection: ^1.14.11
  json_schema: '3.0.1'
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.3.0
  json_serializable: ^4.0.0
  path: ^1.6.2
  test: ^1.6.2
